version: '3.8'
services:
  telegram_ai_bot:
    build: .
    container_name: telegram_ai_bot
    environment:
      TELEGRAM_TOKEN: your:token
      API_OPENAI: your-token
    volumes:
      - telegram_ai_bot:/app/data
    restart: always

volumes:
  telegram_ai_bot:
    external: true
